package cn.com.checknull.model.po;

// Generated 2015-3-17 16:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import cn.com.checknull.model.serializer.DateSerializer;

/**
 * TLogLogin generated by hbm2java
 */
public class TLogLogin extends QueryEntity implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 7319253577325275670L;
	private Long id;
	private String loginName;
	private String operatorName;
	private Long operatorId;
	private Integer type;
	private Integer result;
	private String description;
	private String loginIp;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonSerialize(using = DateSerializer.class)
	private Date time = new Date();
	private String startTime;
	private String endTime;
	public TLogLogin() {
	}

	public TLogLogin(String loginName, String operatorName, Long operatorId,
			Integer type, Integer result, String description, String loginIp,
			Date time) {
		this.loginName = loginName;
		this.operatorName = operatorName;
		this.operatorId = operatorId;
		this.type = type;
		this.result = result;
		this.description = description;
		this.loginIp = loginIp;
		this.time = time;
	}
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}
	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
	public Integer getResult() {
		return this.result;
	}

	public void setResult(Integer result) {
		this.result = result;
	}
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TLogLogin other = (TLogLogin) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	
	@Override
	public void setSort(String sort) {
		
		if (StringUtils.isEmpty(sort) || "id".equals(sort)){
			super.setSort("ID");
		}else if ("loginName".equals(sort)){
			super.setSort("LOGIN_NAME");
		}else if ("operatorName".equals(sort)){
			super.setSort("OPERATOR_NAME");
		}else if ("operatorId".equals(sort)){
			super.setSort("OPERATOR_ID");
		}else if ("type".equals(sort)){
			super.setSort("TYPE");
		}else if ("result".equals(sort)){
			super.setSort("RESULT");
		}else if ("description".equals(sort)){
			super.setSort("DESCRIPTION");
		}else if ("loginIp".equals(sort)){
			super.setSort("LOGIN_IP");
		}else if ("time".equals(sort)){
			super.setSort("TIME");
		}else{
			super.setSort("ID");
		}
	}

}
