package cn.com.checknull.model.po;

// Generated 2015-2-28 11:52:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;

import cn.com.checknull.model.serializer.DateSerializer;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * TOperator generated by hbm2java
 */
public class TOperator extends QueryEntity implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 8151988987778006043L;
	private Long id;
	private Integer gender;
	private String loginName;
	private String password;
	private String realName;
	private String phone;
	private String mobile;
	private String fax;
	private String email;
	private String msn;
	private String qq;
	private Integer errorTimes = 0;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonSerialize(using = DateSerializer.class)
	private Date updateTime;
	private String loginIp;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonSerialize(using = DateSerializer.class)
	private Date loginTime;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonSerialize(using = DateSerializer.class)
	private Date createTime = new Date();
	private Integer status;
	public TOperator() {
	}

	public TOperator(String loginName) {
		this.loginName = loginName;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}
	public Integer getErrorTimes() {
		return this.errorTimes;
	}

	public void setErrorTimes(Integer errorTimes) {
		this.errorTimes = errorTimes;
	}
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	@Override
	public void setSort(String sort) {
		
		if (StringUtils.isEmpty(sort) || "id".equals(sort)){
			super.setSort("ID");
		}else if ("gender".equals(sort)){
			super.setSort("GENDER");
		}else if ("loginName".equals(sort)){
			super.setSort("LOGIN_NAME");
		}else if ("password".equals(sort)){
			super.setSort("PASSWORD");
		}else if ("realName".equals(sort)){
			super.setSort("REAL_NAME");
		}else if ("phone".equals(sort)){
			super.setSort("PHONE");
		}else if ("mobile".equals(sort)){
			super.setSort("MOBILE");
		}else if ("fax".equals(sort)){
			super.setSort("FAX");
		}else if ("email".equals(sort)){
			super.setSort("EMAIL");
		}else if ("msn".equals(sort)){
			super.setSort("MSN");
		}else if ("qq".equals(sort)){
			super.setSort("QQ");
		}else if ("errorTimes".equals(sort)){
			super.setSort("ERROR_TIMES");
		}else if ("updateTime".equals(sort)){
			super.setSort("UPDATE_TIME");
		}else if ("loginIp".equals(sort)){
			super.setSort("LOGIN_IP");
		}else if ("loginTime".equals(sort)){
			super.setSort("LOGIN_TIME");
		}else if ("createTime".equals(sort)){
			super.setSort("CREATE_TIME");
		}else if ("status".equals(sort)){
			super.setSort("STATUS");
		}else{
			super.setSort("ID");
		}
	}
}
