package cn.com.checknull.model.po;

import org.apache.commons.lang3.StringUtils;


// Generated 2015-3-13 14:52:20 by Hibernate Tools 3.4.0.CR1

/**
 * TOperatorRole generated by hbm2java
 */
public class TOperatorRole extends QueryEntity implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 4230947794743282805L;
	private Long id;
	private Long operatorId;
	private String roleIds;

	public TOperatorRole() {
	}

	public TOperatorRole(Long operatorId, String roleIds) {
		this.operatorId = operatorId;
		this.roleIds = roleIds;
	}
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}
	public String getRoleIds() {
		return this.roleIds;
	}

	public void setRoleIds(String roleIds) {
		this.roleIds = roleIds;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TOperatorRole other = (TOperatorRole) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	@Override
	public void setSort(String sort) {
		
		if (StringUtils.isEmpty(sort) || "id".equals(sort)){
			super.setSort("ID");
		}else if ("operatorId".equals(sort)){
			super.setSort("OPERATOR_ID");
		}else if ("roleIds".equals(sort)){
			super.setSort("ROLE_IDS");
		}else{
			super.setSort("ID");
		}
	}
}
