package cn.com.checknull.model.po;

import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;

import cn.com.checknull.model.serializer.DateSerializer;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

// Generated 2015-2-28 11:52:11 by Hibernate Tools 3.4.0.CR1

/**
 * TSysmenu generated by hbm2java
 */
public class TSysmenu extends QueryEntity implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 7500114071288119663L;
	private Long id;
	private String name;
	private String code;
	private String navigateUrl;
	private String icon;
	private TSysmenu parentMenu;
	private Integer level;
	private Integer sequence;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonSerialize(using = DateSerializer.class)
	private Date createTime = new Date();
	private Integer status;
	private Long parentId;
	
	public TSysmenu() {
	}

	public TSysmenu(String name, String navigateUrl, String icon,
			TSysmenu parentMenu, Integer level, Integer sequence, 
			Date createTime, Integer status, String code) {
		this.name = name;
		this.navigateUrl = navigateUrl;
		this.icon = icon;
		this.parentMenu = parentMenu;
		this.level = level;
		this.sequence = sequence;
		this.createTime = createTime;
		this.status = status;
		this.code = code;
	}
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getNavigateUrl() {
		return this.navigateUrl;
	}

	public void setNavigateUrl(String navigateUrl) {
		this.navigateUrl = navigateUrl;
	}
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}
	public TSysmenu getParentMenu() {
		return parentMenu;
	}

	public void setParentMenu(TSysmenu parentMenu) {
		this.parentMenu = parentMenu;
	}
	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Long getParentId() {
		return parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}
	@Override
	public void setSort(String sort) {
		
		if (StringUtils.isEmpty(sort) || "id".equals(sort)){
			super.setSort("ID");
		}else if ("name".equals(sort)){
			super.setSort("NAME");
		}else if ("code".equals(sort)){
			super.setSort("CODE");
		}else if ("navigateUrl".equals(sort)){
			super.setSort("NAVIGATE_URL");
		}else if ("icon".equals(sort)){
			super.setSort("ICON");
		}else if ("level".equals(sort)){
			super.setSort("LEVEL");
		}else if ("sequence".equals(sort)){
			super.setSort("SEQUENCE");
		}else if ("createTime".equals(sort)){
			super.setSort("CREATE_TIME");
		}else if ("status".equals(sort)){
			super.setSort("STATUS");
		}else if ("parentId".equals(sort)){
			super.setSort("PARENT_ID");
		}else{
			super.setSort("ID");
		}
	}
}
