package cn.com.checknull.model.po;

import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;

import cn.com.checknull.model.serializer.DateSerializer;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

// Generated 2015-3-17 16:18:12 by Hibernate Tools 3.4.0.CR1

/**
 * TSysconfig generated by hbm2java
 */
public class TSysconfig extends QueryEntity implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 5741331356522050486L;
	private Long id;
	private String paramName;
	private String paramCode;
	private String paramValue;
	private String description;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonSerialize(using = DateSerializer.class)
	private Date createTime = new Date();
	
	public TSysconfig() {
	}

	public TSysconfig(String paramName, String paramCode, String paramValue,
			String description, Date createTime) {
		this.paramName = paramName;
		this.paramCode = paramCode;
		this.paramValue = paramValue;
		this.description = description;
		this.createTime = createTime;
	}
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}
	public String getParamCode() {
		return this.paramCode;
	}

	public void setParamCode(String paramCode) {
		this.paramCode = paramCode;
	}
	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	@Override
	public void setSort(String sort) {
		
	if (StringUtils.isEmpty(sort) || "id".equals(sort)){
		super.setSort("ID");
	}else if ("paramName".equals(sort)){
		super.setSort("PARAM_NAME");
	}else if ("paramCode".equals(sort)){
		super.setSort("PARAM_CODE");
	}else if ("paramValue".equals(sort)){
		super.setSort("PARAM_VALUE");
	}else if ("description".equals(sort)){
		super.setSort("DESCRIPTION");
	}else if ("createTime".equals(sort)){
		super.setSort("CREATE_TIME");
	}else{
		super.setSort("ID");
	}
}
}
