package cn.com.checknull.model.po;

// Generated 2015-3-2 14:20:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;

import cn.com.checknull.model.serializer.DateSerializer;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * TSyspriv generated by hbm2java
 */
public class TSyspriv extends QueryEntity implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 6545739685137155618L;
	private Long id;
	private String code;
	private String name;
	private String iconCls;
	private String icon;
	private String method;
	private TSysmenu menu;
	private Integer sequence;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonSerialize(using = DateSerializer.class)
	private Date createTime = new Date();
	private Integer status;
	private Long menuId;
	
	public TSyspriv() {
	}

	public TSyspriv(Long id) {
		this.id = id;
	}

	public TSyspriv(Long id, String code, String name,
			String iconCls, String method, Integer sequence, 
			Date createTime, Integer status) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.iconCls = iconCls;
		this.method = method;
		this.sequence = sequence;
		this.createTime = createTime;
		this.status = status;
	}
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getIconCls() {
		return iconCls;
	}

	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}
	
	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getMethod() {
		return method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public TSysmenu getMenu() {
		return menu;
	}

	public void setMenu(TSysmenu menu) {
		this.menu = menu;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Long getMenuId() {
		return menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}
	@Override
	public void setSort(String sort) {
		
		if (StringUtils.isEmpty(sort) || "id".equals(sort)){
			super.setSort("ID");
		}else if ("name".equals(sort)){
			super.setSort("NAME");
		}else if ("code".equals(sort)){
			super.setSort("CODE");
		}else if ("iconCls".equals(sort)){
			super.setSort("ICON_CLS");
		}else if ("icon".equals(sort)){
			super.setSort("ICON");
		}else if ("method".equals(sort)){
			super.setSort("METHOD");
		}else if ("sequence".equals(sort)){
			super.setSort("SEQUENCE");
		}else if ("createTime".equals(sort)){
			super.setSort("CREATE_TIME");
		}else if ("status".equals(sort)){
			super.setSort("STATUS");
		}else if ("menuId".equals(sort)){
			super.setSort("MENU_ID");
		}else{
			super.setSort("ID");
		}
	}
}
